# Generated by Django 4.1 on 2022-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="user",
            field=models.CharField(default="default_user", max_length=64),
            preserve_default=False,
        ),
    ]
