# Generated by Django 4.1 on 2022-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listings_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="bidder_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
