# Generated by Django 4.1 on 2022-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listings_bidder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
