# Generated by Django 4.1 on 2022-08-30 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_listings_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bids",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bids",
            name="user",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
