# Generated by Django 4.1 on 2022-08-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_bids_bid_bids_listing_bids_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="bidder_id",
        ),
    ]
