# Generated by Django 4.1 on 2022-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_remove_listings_bidder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
