# Generated by Django 4.1 on 2022-08-30 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_listings_current_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
